name=ACS712
version=1.15.4
author=Rob Tillaart 
maintainer=Rob Tillaart <rob.tillaart@gmail.com>
sentence=ACS712 library for Arduino. Current measurement, tested with RobotDyn ACDC 20A Module.
paragraph=ACS712 library for Arduino. Current measurement, tested with RobotDyn ACDC 20A Module.
category=Display
url=https://github.com/RobTillaart/ACS712
architectures=*
includes=ACS712XX.h
