; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino

lib_deps =
    symlink://../shared_libs/ACS712
    symlink://../shared_libs/Adafruit_NeoPixel
    symlink://../shared_libs/Ethernet/src
    symlink://../shared_libs/PubSubClient/src
    symlink://../shared_libs/arduino-CAN
    symlink://../shared_libs/L298N/src
    